Textinator/Textinator/urls.py
# -*- coding: utf-8 -*-
"""Textinator URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django_registration.backends.one_step.views import RegistrationView
from django.views.i18n import JavaScriptCatalog


from filebrowser.sites import site

from . import views

paths = [
    path('', views.index),
    path('admin/filebrowser/', site.urls),
    path('admin/', admin.site.urls),
    path('accounts/register/',
        RegistrationView.as_view(success_url='/{}'.format(settings.ROOT_URLPATH)),
        name='django_registration_register'),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('projects/', include('projects.urls')),
    path('tools/', include('toolbox.urls')),
    path('users/', include('users.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

if 'scientific_survey' in settings.INSTALLED_APPS:
    paths += [
        path('survey/', include('scientific_survey.urls'))
    ]

if 'rosetta' in settings.INSTALLED_APPS:
    paths += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

urlpatterns = [
    path(settings.ROOT_URLPATH, include(paths))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Textinator/users/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('settings', views.user_settings, name='textinator_settings')
]

Textinator/projects/models.py
# -*- coding: utf-8 -*-
import random
import secrets
import time
import logging
import json
import hashlib
from collections import defaultdict
from itertools import groupby
from operator import itemgetter

from django.db import models, transaction
from django.db.models.sql.where import ExtraWhere, AND
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.cache import caches
from django.contrib.postgres.search import SearchVectorField, SearchVector
from django.contrib.postgres.indexes import GinIndex

from filebrowser.fields import FileBrowseField
from colorfield.fields import ColorField
from model_clone import CloneMixin
from model_clone.utils import create_copy_of_instance

from Textinator.ext import RegConfigField

from .datasources import *
from .helpers import *
from .model_helpers import *


logger = logging.getLogger(__name__)


class CommonModel(models.Model):
    """
    Abstract model containing the fields for creation and update dates, as well as a stub for `to_json` method.
    """
    dt_created = models.DateTimeField(null=True, default=timezone.now, verbose_name=_("Created at"),
        help_text=_("Autofilled"))
    dt_updated = models.DateTimeField(null=True, verbose_name=_("Updated at"),
        help_text=_("Autofilled"))

    class Meta:
        abstract = True

    def to_json(self, dt_format=None):
        return {
            'created': self.dt_created.strftime(dt_format),
            'updated': self.dt_updated.strftime(dt_format)
        } if dt_format else {}

    def save(self, *args, **kwargs):
        self.dt_updated = timezone.now()
        super(CommonModel, self).save(*args, **kwargs)


class PostProcessingMethod(CommonModel):
    """
    Holds function names to the post-processing methods that can be applied directly to textual data.
    Eligible methods are currently being pulled from `projects/helpers.py`, which is not a very elegant solution.

    **NOTE**: this functionality is currently inactive and is a candidate for removal/overhaul in future releases.
    """
    class Meta:
        verbose_name = _('post-processing method')
        verbose_name_plural = _('post-processing methods')

    name = models.CharField(_("name"), max_length=50,
        help_text=_("Verbose name"))
    helper = models.CharField(_("helper function name"), max_length=50,
        help_text=_("Name as specified in `projects/helpers.py`"))

    def __str__(self):
        return self.name


class DataSource(CommonModel):
    """
    Holds a **definition** of a datasource. Currently we support 4 `source_types`:

    - plain text -- input text directly in the admin interface (mostly for testing)
    - plain text files -- a bunch of files hosted on the same server as Textinator
    - JSON files -- a bunchf of JSON files hosted on the same server as Textinator
    - Texts API -- a REST API that will be used for getting each datapoint (the endpoint should be specified)

    Texts API specification is available in the `example_texts_api` folder of the GitHub repository.

    DataSource specifies 3 different formattings:

    - plain text (without line breaks or tabs preserved)
    - formatted text (with line breaks and tabs preserved)
    - markdown

    By default each DataSource is private, unless `is_public` switch is on.

    `owner` of the DataSource is set automatically and is nullable.
    The reason behind allowing NULL values is that the data might be owned by the institution,
    not by the user and might also have projects connected to it.
    If people want their datasource deleted together with their user account,
    they need to request a manual deletion.
    """

    INTERACTIVE = "Interact"

    class Meta:
        verbose_name = _('data source')
        verbose_name_plural = _('data sources')
        permissions = (
            ('view_this_datasource', 'View this data source'),
            ('change_this_datasource', 'Change this data source'),
            ('delete_this_datasource', 'Delete this data source'),
        )

    name = models.CharField(_("dataset name"), max_length=50)
    source_type = models.CharField(_("dataset type"), max_length=10, choices=settings.DATASOURCE_TYPES)
    spec = models.TextField(_("specification"), null=False,
        help_text=_("in a JSON format")) # json spec of the data source
    post_processing_methods = models.ManyToManyField(PostProcessingMethod, blank=True,
        verbose_name=_("post-processing methods"))
    language = models.CharField(_("language"), max_length=10, choices=settings.LANGUAGES,
        help_text=_("Language of this data source")
    )
    search_config = RegConfigField(_("PostgreSQL search config"), null=True, blank=True)
    formatting = models.CharField(_('formatting'), max_length=3, choices=settings.FORMATTING_TYPES,
        help_text=_("text formating of the data source"))
    is_public = models.BooleanField(_("is public?"), default=False,
        help_text=_("Whether to make data source available to other Textinator users"))
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, verbose_name=_("owner"))

    def save(self, *args, **kwargs):
        if not self.search_config:
            lang_dict = dict(settings.LANGUAGES)
            sconf_dict = settings.LANG_SEARCH_CONFIG
            search_config = sconf_dict.get(
                self.language,
                lang_dict.get(self.language, 'english')
            ).lower()
            self.search_config = search_config
        super(CommonModel, self).save(*args, **kwargs)

    @classmethod
    def type2class(cls, source_type):
        return globals().get(source_type + 'Source')

    def postprocess(self, text):
        pp = self.post_processing_methods.all()
        if pp:
            for method in pp:
                text = globals().get(method.helper, lambda x: x)(text)
        return text

    def _load(self):
        source_cls = DataSource.type2class(self.source_type)
        if self.owner:
            spec = json.loads(self.spec.replace('\r\n', ' ').replace('\n', ' '))
            spec['username'] = self.owner.username
            ds_instance = source_cls(spec)
        else:
            ds_instance = source_cls(self.spec.replace('\r\n', ' ').replace('\n', ' '))
        return ds_instance

    def get(self, idx):
        ds_instance = self._load()
        return ds_instance[idx]

    def size(self):
        ds_instance = self._load()
        return ds_instance.size()

    def __str__(self):
        return "{} ({})".format(self.name, self.language)

    @property
    def is_interactive(self):
        return self.source_type == DataSource.INTERACTIVE


class MarkerAction(CommonModel):
    """
    Specifies an action that shows up after right-clicking the marker.
    Each action is implemented as a JavaScript plugin that should exist in `static/scripts/labeler_plugins` folder
    along with a specification of how to implement your own plugins if necessary.
    """

    class Meta:
        verbose_name = _('marker action')
        verbose_name_plural = _('marker actions')

    name = models.CharField(_("name"), max_length=50, unique=True)
    description = models.TextField(_("description"), null=False)
    file = models.CharField(_("file name"), max_length=100,
        help_text=_("a name of the JS plugin file in the `/static/scripts/labeler_plugins` directory"))
    admin_filter = models.CharField(_("type of admin filter"), max_length=50, blank=True, null=True,
        help_text=_(
            """
            Specifies the filter type in the data explorer interface (one of 'boolean', 'range').
            If empty, then this action will be excluded from data explorer.
            """
        )) # What types? So far found: boolean, range

    def __str__(self):
        return self.description

    def to_json(self, dt_format=None):
        res = super(MarkerAction, self).to_json(dt_format=dt_format)
        res.update({
            'name': self.name,
            'admin_filter': self.admin_filter
        })
        return res


class Marker(CommonModel):
    """
    Holds the **definition** for each unit of annotation in Textinator, called `Marker`.
    We create each `Marker` only when creating a new project and can re-use `Markers` between the projects
    (all `Markers` are available to all users).
    """
    name = models.CharField(_("name"), max_length=50,
        help_text=_("The display name of the marker (max 50 characters)"))
    code = models.CharField(_("code"), max_length=25, unique=True, blank=True,
        help_text=_("Marker's nickname used internally"))
    color = ColorField(_("color"), help_text=_("Color for the annotated text span"))
    shortcut = models.CharField(_("keyboard shortcut"), max_length=10, null=True, blank=True,
        help_text=_("Keyboard shortcut for annotating a piece of text with this marker"))
    suggestion_endpoint = models.URLField(max_length=200, null=True, blank=True,
        help_text=_("Endpoint for the Suggestions API"))

    class Meta:
        verbose_name = _('marker')
        verbose_name_plural = _('markers')
        permissions = (
            ('change_this_marker', 'Change this marker'),
            ('delete_this_marker', 'Delete this marker'),
        )


    def save(self, *args, **kwargs):
        if not self.code:
            self.code = "{}_{}_{}".format(self.name_en[:3].upper(), str(int(time.time())), secrets.randbelow(10000))
        super(Marker, self).save(*args, **kwargs)

    def is_part_of_relation(self):
        """
        Check whether a given marker is part of definition for any `Relation`
        """
        return bool(Relation.objects.filter(models.Q(pairs__first=self) | models.Q(pairs__second=self)).all())

    def __str__(self):
        return self.name

Textinator/templates/filebrowser/createdir.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load static i18n fb_tags fb_csrf fb_compat %}

<!-- STYLESHEETS -->
{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}
{% block coltype %}colM{% endblock %}

<!-- BREADCRUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
<div id="content-main">
  <!-- POP-UP BREADCRUMBS -->
  {% if query.pop %}
    {% include "filebrowser/include/breadcrumbs.html" %}
  {% endif %}
  <form action="{% query_string '' 'p' %}" method="post">
    {% fb_csrf_token %}
    <div>
      {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
      <fieldset class="card card-info card-outline">
        <div class="card-header">
          <h4>{% trans "New Folder" %}</h4>
        </div>
        <div class="card-body">
          {% if form.custom_action.errors %}
            <div class="form-row errors">
              {{ form.custom_action.errors }}
            </div>
          {% endif %}
          <table class="table table-borderless" style="font-size: 13px;">
            <tbody>
              <tr>
                <td><label class="required" for="id_dir_name">{{ form.name.label }}</label></td>
                <td>
                  {{ form.name }}
                  <p class="help">
                    {{ form.name.help_text|safe }}
                    {% if settings_var.NORMALIZE_FILENAME or settings_var.CONVERT_FILENAME %}
                      <br />
                      {% if settings_var.NORMALIZE_FILENAME %}
                        {% trans "The Name will be normalized by converting or stripping all non-standard characters." %} <br />
                      {% endif %}
                      {% if settings_var.CONVERT_FILENAME %}
                        {% trans "The Name will be converted to lowercase. Spaces will be replaced with underscores." %}
                      {% endif %}
                    {% endif %}
                  </p>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </fieldset>
      <div class="card card-info card-outline">
        <div class="card-header">
          <h3 class="card-title">
            <i class="fas fa-edit"></i>
            Actions
          </h3>
        </div>
        <div class="card-body">
          <div class="form-group">
            <input type="submit" value="{% trans 'Submit' %}" class="default btn btn-outline-success form-control" />
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

Textinator/templates/filebrowser/delete_confirm.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load static i18n fb_tags fb_versions fb_compat %}

<!-- BREADCRBUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
  <!-- POP-UP BREADCRUMBS -->
  {% if query.pop %}
    {% include "filebrowser/include/breadcrumbs.html" %}
  {% endif %}

  <div class="card card-danger card-outline">
    <div class="card-header">
      <p>{% blocktrans with fileobject.filename as escaped_object %}Are you sure you want to delete the {{ object_name }} "{{ escaped_object }}"? All of the following related items will be deleted:{% endblocktrans %}</p>
      <ul>
        <li>{{ fileobject.filename }}</li>
      </ul>

      {% if filelisting %}
        <ul>
          {% for item in filelisting %}
            <li>{{ item.path_relative_directory }}</li>
          {% endfor %}
        <ul>
      {% endif %}
      {% if additional_files %}
        <ul>
          <li>{% blocktrans with additional_files as escaped_object %}... and {{ escaped_object }} more Files.{% endblocktrans %}</li>
        </ul>
      {% endif %}
    </div>

    <div class="card-body">
      <form action="{% url 'filebrowser:fb_delete' %}{% query_string %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-outline-danger" value="{% trans "Yes, I'm sure" %}" />
      </form>
    </div>
  </div>
{% endblock %}

Textinator/templates/filebrowser/detail.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load static i18n fb_tags fb_versions fb_compat %}

<!-- STYLESHEETS -->
{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
{% endblock %}

<!-- JAVASCRIPTS -->
{% block extrahead %}
  {{ block.super }}
  <script type="text/javascript" src="{% static_jquery %}"></script>
  <script type="text/javascript" src="{% static "admin/js/jquery.init.js" %}"></script>
  <script type="text/javascript">
  (function($) {
    $(document).ready(function() {
      // remove edit module if no actions are given
      if ($("select#id_custom_action").find("option").length <= 1) {
        $("fieldset#fieldset_edit").hide();
      }
    });
  })(django.jQuery);
  </script>
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}
{% block coltype %}colM{% endblock %}

<!-- BREADCRBUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
  <div id="content-main">
    <!-- POP-UP BREADCRUMBS -->
    {% if query.pop %}
      {% include "filebrowser/include/breadcrumbs.html" %}
    {% endif %}
    <form action="{% query_string "" "filter_date,filter_type,q,p" %}" method="post">{% csrf_token %}
      <div>
        {% if form.errors %}<p class="errornote">{% trans 'Please correct the following errors.' %}</p>{% endif %}
        <fieldset class="module aligned">
          <div class="form-row field-{{ form.name.name }}{% if form.name.errors %} errors{% endif %}">
            {% if form.name.errors %}{{ form.name.errors }}{% endif %}
            <div>
              <label class="required" for="id_name">{{ form.name.label }}</label>
              {{ form.name }}
              {% if form.name.help_text %}<p class="help">{{ form.name.help_text|safe }}</p>{% endif %}
            </div>
          </div>
        </fieldset>
        <fieldset class="card card-info card-outline" id="fieldset_edit">
          <div class="card-header">
            <h4>{% trans "Edit" %}</h4>
          </div>
          <div class="card-body">
            {% if form.custom_action.errors %}
              <div class="form-row errors">
                {{ form.custom_action.errors }}
              </div>
            {% endif %}
            <table class="table table-borderless" style="font-size: 13px;">
              <tbody>
                <tr>
                  <td><label class="required" for="id_custom_action">{{ form.custom_action.label }}</label></td>
                  <td>
                    {{ form.custom_action }}
                    {% if form.custom_action.help_text %}<p class="help">{{ form.custom_action.help_text|safe }}</p>{% endif %}
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </fieldset>
        {% if fileobject.filetype == "Folder" %}
          <fieldset class="card card-info card-outline">
            <div class="card-header">
              <h4>{% trans "Folder Information" %}</h4>
            </div>
            <div class="card-body">
              <table class="table table-borderless" style="font-size: 13px;">
                <tbody>
                  <tr>
                    <td><label>{% trans "Date" %}</label></td>
                    <td>
                      {{ fileobject.datetime|date:"N j, Y" }}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </fieldset>
        {% endif %}
        {% if fileobject.filetype != "Folder" %}
          <fieldset class="card card-info card-outline">
            <div class="card-header">
              <h4>{% trans "File Information" %}</h4>
            </div>
            <div class="card-body">
              <table class="table table-borderless" style="font-size: 13px;">
                <tbody>
                  <tr>
                    <td><label>{% trans "URL" %}</label></td>
                    <td>
                      <a href="{{ fileobject.url }}">{{ fileobject.url }}</a>
                    </td>
                  </tr>
                  <tr>
                    <td><label>{% trans "Filesize" %}</label></td>
                    <td>
                      {{ fileobject.filesize|filesizeformat }}
                    </td>
                  </tr>
                  <tr>
                    <td><label>{% trans "Date" %}</label></td>
                    <td>
                      {{ fileobject.datetime|date:"N j, Y" }}
                    </td>
                  </tr>
                  {% if fileobject.filetype == "Image" %}
                    <tr>
                      <td><label>{% trans "Size" %}</label></td>
                      <td>
                        {{ fileobject.width }} x {{ fileobject.height }} px
                      </td>
                    </tr>
                  {% endif %}
                </tbody>
              </table>
            </div>
          </fieldset>
        {% endif %}
        {% if fileobject.filetype == "Image" %}
          <fieldset class="card card-info card-outline">
            <div class="card-header">
              <h4>{% trans "Image Versions" %}</h4>
            </div>
            <div class="card-body">
              <table class="table table-borderless" style="font-size: 13px;">
                <tbody>
                  {% if settings_var.ADMIN_THUMBNAIL %}
                    <tr>
                      <td><label>{% trans "Thumbnail" %}</label></td>
                      <td>
                        <img src="{% version fileobject.path settings_var.ADMIN_THUMBNAIL %}" title="{% trans 'View Image' %}" />
                      </td>
                    </tr>
                  {% endif %}
                  {% if settings_var.ADMIN_VERSIONS %}
                    {% for version in settings_var.ADMIN_VERSIONS %}
                      {% version fileobject version as image_version %}
                      {% version_setting version %}
                      <tr>
                        <td><label>{{ version_setting.verbose_name }}</label></td>
                        <td>
                          <img src="{{ image_version.url }}" />
                        </td>
                      </tr>
                    {% endfor %}
                  {% endif %}
                </tbody>
              </table>
            </div>
          </fieldset>
        {% endif %}
        <div class="card card-info card-outline">
          <div class="card-header">
            <h3 class="card-title">
              <i class="fas fa-edit"></i>
              Actions
            </h3>
          </div>
          <div class="card-body">
            <div class="form-group">
              <input type="submit" value="{% trans 'Save' %}" class="default btn btn-outline-success form-control" />
            </div>
            <div class="form-group">
              <input type="submit" value="{% trans 'Save and continue editing' %}" class="btn btn-outline-info form-control" name="_continue" />
            </div>
            <div class="form-group">
              <p class="deletelink-box">
                <a href="{% url 'filebrowser:fb_delete_confirm' %}{% query_string %}" class="btn btn-outline-danger form-control deletelink">{% trans "Delete" %}</a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

Textinator/templates/filebrowser/upload.html
{% extends "admin/base_site.html" %}

<!-- LOADING -->
{% load static i18n l10n fb_tags fb_compat %}

<!-- STYLESHEETS -->
{% block extrastyle %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
    <link rel="stylesheet" type="text/css" href="{% static "filebrowser/css/filebrowser.css" %}" />
{% endblock %}

<!-- JAVASCRIPTS -->
{% block extrahead %}
  {{ block.super }}
  <script type="text/javascript" src="{% static_jquery %}"></script>
  <script type="text/javascript" src="{% static "admin/js/jquery.init.js" %}"></script>
  <script type="text/javascript" src="{% static "admin/js/collapse.min.js" %}"></script>
  <script type="text/javascript" src="../../jsi18n/"></script>
  <script type="text/javascript" src="{% static "filebrowser/js/fileuploader.js" %}"></script>
  <script type="text/javascript">
    (function($){
      $(document).ready(function() {
        var uploader = new qq.FileUploader({
          element: $('#file-uploader > div').get(0),
          action: '{% url 'filebrowser:fb_do_upload' %}',

          template: '<div class="qq-uploader">' +
              '<div class="qq-upload-drop-area"><span>{% trans "Drop files here to upload" %}</span></div>' +
              '<div class="qq-upload-button">{% trans "Upload a file" %}</div>' +
              '<div class="qq-upload-list"></div>' +
          '</div>',

          fileTemplate: '<div>' +
              '<span class="qq-upload-file"></span>' +
              '<span class="qq-upload-spinner"></span>' +
              '<span class="qq-upload-size"></span>' +
              '<a class="qq-upload-cancel" href="#">{% trans "Cancel" %}</a>' +
              '<span class="qq-upload-failed-text">{% trans "Failed" %}</span>' +
              '<span class="qq-upload-complete"></span>' +
              '<div class="progress-bar"><div class="content"></div></div>' +
          '</div>',

          params: { 'csrf_token': '{{ csrf_token }}',
                    'csrf_name': 'csrfmiddlewaretoken',
                    'csrf_xname': 'X-CSRFToken',
                    'folder': '{{ query.dir|escapejs }}', },

          allowedExtensions: {% get_file_extensions request.GET %},
          sizeLimit: {{ settings_var.MAX_UPLOAD_SIZE|unlocalize }},
          minSizeLimit: 0,
          debug: false,
          // messages
          messages: {
            typeError: "{% trans "{file} has invalid extension. Only {extensions} are allowed." %}",
            sizeError: "{% trans "{file} is too large, maximum file size is {sizeLimit}." %}",
            minSizeError: "{% trans "{file} is too small, minimum file size is {minSizeLimit}." %}",
            emptyError: "{% trans "{file} is empty, please select files again without it." %}",
            onLeave: "{% trans "The files are being uploaded, if you leave now the upload will be cancelled." %}"
          },

          getItem: function(id) {
            var items = $(this.element).find('.qq-upload-list > div').get();
            var item = items.pop();

            while (typeof item != "undefined") {
                if (item.qqFileId == id) {
                    return $(item);
                }
                item = items.pop();
            }
          },
          onProgress: function(id, fileName, loaded, total){
            var bar = this.getItem(id).find('.progress-bar .content');
            var new_width = '' + (loaded/total * 100) + '%';
            bar.css('width', new_width);
          },
          onComplete: function(id, fileName, resp){
            if (resp.success) {
              this.getItem(id).find('.qq-upload-file').html('<a href="' + resp.url + '">'+ resp.filename + '</a>');
            }
          },
          showMessage: function(message){ alert(message); }
        });
      });
    })(django.jQuery);
  </script>
{% endblock %}

<!-- COLTYPE/BODYCLASS -->
{% block bodyclass %}change-form filebrowser{% if query.pop %} popup{% endif %}{% endblock %}
{% block coltype %}colM{% endblock %}

<!-- BREADCRUMBS -->
{% block breadcrumbs %}{% include "filebrowser/include/breadcrumbs.html" %}{% endblock %}

<!-- CONTENT -->
{% block content %}
  <div id="content-main">
    <!-- POP-UP BREADCRUMBS -->
    {% if query.pop %}
      {% include "filebrowser/include/breadcrumbs.html" %}
    {% endif %}
    <form>
      <div>
        <fieldset class="module aligned">
          <div class="form-row" id="file-uploader">
            <div class="form-col">
              <noscript>
                {% trans "Please enable Javascript to upload files." %}
              </noscript>
            </div>
          </div>
          <div class="form-row" id="back-button">
            {% with breadcrumbs|last as last_breadcrumb %}
              <a class="btn btn-sm btn-outline-primary" href="{% url 'filebrowser:fb_browse' %}{% query_string "" "q,dir,filename,p" %}&amp;dir={{ last_breadcrumb.1|urlencode }}">{% trans 'Return to uploads' %}</a>
            {% endwith %}
          </div>
        </fieldset>
        <fieldset class="card card-info card-outline">
          <div class="card-header">
            <h4>{% trans "Help" %}</h4>
          </div>
          <div class="card-body">
            <table class="table table-borderless" style="font-size: 13px;">
              <tbody>
                <tr>
                  <td><label class="required">{% trans "Allowed" %}</label></td>
                  <td>
                    {% for extension in settings_var.EXTENSIONS.items %}
                      {% ifnotequal extension.0 'Folder' %}
                        <strong>{% trans extension.0|safe %}</strong> ({{ extension.1|join:", "|safe }})<br />
                      {% endifnotequal %}
                    {% endfor %}
                  </td>
                </tr>
                <tr>
                  <td><label class="required">{% trans "Max. Filesize" %}</label></td>
                  <td>
                    {{ settings_var.MAX_UPLOAD_SIZE|filesizeformat }}
                  </td>
                </tr>
                {% if settings_var.NORMALIZE_FILENAME or settings_var.CONVERT_FILENAME %}
                  <tr>
                    <td><label class="required">{% trans "Filename" %}</label></td>
                    <td>
                      {% if settings_var.NORMALIZE_FILENAME %}
                        {% trans "The Name will be normalized by converting or stripping all non-standard characters." %}
                      {% endif %}
                      {% if settings_var.CONVERT_FILENAME %}
                        {% trans "The Name will be converted to lowercase. Spaces will be replaced with underscores." %}
                      {% endif %}
                    </td>
                  </tr>
                {% endif %}
              </tbody>
            </table>
          </div>
        </fieldset>
      </div>
    </form>
  </div>
{% endblock %}