Textinator/Textinator/urls.py
# -*- coding: utf-8 -*-
"""Textinator URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django_registration.backends.one_step.views import RegistrationView
from django.views.i18n import JavaScriptCatalog


from filebrowser.sites import site

from . import views

paths = [
    path('', views.index),
    path('admin/filebrowser/', site.urls),
    path('admin/', admin.site.urls),
    path('accounts/register/',
        RegistrationView.as_view(success_url='/{}'.format(settings.ROOT_URLPATH)),
        name='django_registration_register'),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('projects/', include('projects.urls')),
    path('tools/', include('toolbox.urls')),
    path('users/', include('users.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
]

if 'scientific_survey' in settings.INSTALLED_APPS:
    paths += [
        path('survey/', include('scientific_survey.urls'))
    ]

if 'rosetta' in settings.INSTALLED_APPS:
    paths += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

urlpatterns = [
    path(settings.ROOT_URLPATH, include(paths))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Textinator/projects/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    #path("exports/settings", views.export_settings, name="export_settings"),
    path("import/", views.importer, name='import'),
    path('<proj>/flag/text', views.flag_text, name='flag_text'),
    path('<proj>/flag/batch', views.flag_batch, name='flag_batch'),
    path('<proj>/flagged/search', views.flagged_search, name='flagged_search'),
    path('<proj>/recorded/search', views.recorded_search, name='recorded_search'),
    path('<proj>/article/new', views.new_article, name='new_article'),
    path('<proj>/article/undo_last', views.undo_last, name='undo_last'),
    path('<proj>/record_datapoint/', views.record_datapoint, name="record_datapoint"),
    path('<proj>/edit/', views.editing, name="editing"),
    path('<proj>/review/', views.review, name='review'),
    path('<proj>/join', views.join_or_leave_project, name='join_or_leave'),
    path('<proj>/time_report', views.time_report, name='time_report'),
    path('<proj>/explorer', views.data_explorer, name='data_explorer'),
    path('<proj>/export', views.export, name='data_exporter'),
    path('<proj>/explorer/inputs/<inp>/delete', views.async_delete_input, name='async_delete_input'),
    path("<proj>/get/annotations", views.get_annotations, name="get_annotations"),
    path("<proj>/get/context", views.get_context, name="get_context"),
    path("<proj>/get/batch", views.get_batch, name="get_batch"),
    path('profile/<username>/', views.profile, name='profile'),
    path('<pk>/', views.DetailView.as_view(), name='detail'),
    path("<pk>/chart/start", views.chart_start, name="chart_start"),
    path("<pk>/chart/status", views.chart_status, name="chart_status"),
    #path("<pk>/charts/users/timing", views.user_timing_chart_json, name="user_timing_chart"),
    #path("<pk>/charts/users/progress", views.user_progress_chart_json, name="user_progress_chart"),
    #path("<pk>/charts/datasources/sizes", views.datasource_size_chart_json, name="datasource_size_chart"),
    path("get/data/<source_id>/<dp_id>", views.get_data, name="get_data"),
    path('', views.IndexView.as_view(), name='index')
]

Textinator/users/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('settings', views.user_settings, name='textinator_settings')
]

Textinator/templates/rosetta/base.html
{% load static %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block pagetitle %}Rosetta{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'admin/css/forms.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'admin/css/changelists.css' %}" type="text/css"/>
    <style type="text/css">
        .pulled-right {
            float: right;
        }
    </style>
    <style type="text/css" media="screen">
        {% include 'rosetta/css/rosetta.css' %}
    </style>
    {% block extra_styles %}{% endblock %}
    <script src="//code.jquery.com/jquery-1.12.4.min.js"></script>
    <script type="text/javascript">
        {% include 'rosetta/js/rosetta.js' %}
    </script>
</head>
<body>
    <div id="container">
        <div id="header">
            {% block header %}
            <div id="branding">
                <h1 id="site-name"><a href="{% url 'rosetta-file-list' po_filter='project' %}">Textinator Translations</a> </h1>
            </div>
            <a href="{% url 'projects:index' %}" class="pulled-right">Back to Textinator</a>
            {% endblock %}
        </div>
        <div class="breadcrumbs">{% block breadcumbs %}{% endblock %}</div>
        <div id="content" class="flex">
            {% block main %}{% endblock %}
        </div>
        <div id="footer" class="breadcumbs">
            <a href="https://github.com/mbi/django-rosetta">Rosetta</a> <span class="version">{{version}}</span>
        </div>
    </div>
</body>
</html>